language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ramakishore/dock-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramakishore/dock-react npm run test -- --coverage